### ISSUE TITLE
Time-consuming step in AlignGraph

### ISSUE THREAD

**Issue by danshu** [baoe/AlignGraph#28]
Hi,

I have been running AlignGraph for two days. I thought the most time-consuming stelp would be blat. But in the "temp" folder, I have all "_contigs_genome.*.psl" ready, but for "_reads_genome.*.bowtie", only 109/4312 have been finished. AlignGraph uses only one thread doing this step and it takes about 15 mins to generate one "_reads_genome.*.bowtie" file.  Is this expected and can AlignGraph use multiple thread in this step?

Best,
Danshu

**Comment by baoe** [comment]
Hi, Danshu,

AlignGraph runs Bowtie2 with 8 threads rather than 1, but even if with more threads, it will still takes a lot of time to align short reads to 4312 reference contigs/scaffolds. Maybe you could combine the 4312 reference contigs/scaffolds into 1 with sufficient N's in between and then run AlignGraph. In this way, time can be greatly saved.  

Regards,
Bao

**Comment by danshu** [comment]
Thanks！
